### ISSUE TITLE
Get Dimension ID

### ISSUE THREAD

**Issue by Twings94** [thibaulthenry/cosmos#2]
Hi, it was possible to get the Dimension ID ?

**Comment by thibaulthenry** [comment]
Hey, you can know the dimension type of a world using the following command 

`cosmos info <world-name>`

![dim](https://user-images.githubusercontent.com/25883318/103442011-9a9de380-4c52-11eb-98d9-b30267bfb86f.png)

Why do you need the ID exactly ? 0 for overworld, -1 for nether and 1 for end
