### ISSUE TITLE
Import world

### ISSUE THREAD

**Issue by Pedrulo213** [thibaulthenry/cosmos#4]
Hello, i have a problem.
When i try to import a world, it crash:
java.lang.Error: ServerHangWatchdog detected that a single server tick took 60,00 seconds (should be max 0.05)
My server has 16 GB RAM, i think thats enough...
What can i do?

**Comment by thibaulthenry** [comment]
Hello, 

Well this is not really a log about the crash itself but your server stopped responding after that you used the command. 
I see you joined the Cosmos discord, I'll text you to know more about your problem.

**Comment by Pedrulo213** [comment]
Don't worry, i've already fixed it, it was a incompatibility of the mods.
Thanks.

**Comment by thibaulthenry** [comment]
That's nice, I'm glad you fixed it :)
Thanks for using Cosmos !
